### PR TITLE
correct package reference paths

### PR DESCRIPTION
**Pull request by yirenjun**

### CODE REVIEW

**Comment by mxpr** [comment]
Can you provide a sample usage with this change? I was testing it out from the command line and sadly the usage I outlined in the readme no longer works. I will update it for steps on how to run the tests (thanks for this indirect reminder!)

This is how it previously worked:

```
$ cd ios-build-utils
$ python
>>> from ipa_packager import IpaPackager
>>> ipa = IpaPackager("/path/to/MyApp.app","/output/path/MyApp.ipa")
>>> ipa.package()
```

Pull request #8 will make it more practical to use.

**Comment by yirenjun** [comment]
image

I use this dependency package through git submodule, In my django project, it must use relative reference path

**Comment by dmueller39** [comment]
@yirenjun 
Your commit https://github.com/yirenjun/ios-build-utils/commit/54b10f47af99c5991f7b9d57d6ec27bb36291883 is very helpful. 

On the other hand https://github.com/yirenjun/ios-build-utils/commit/feffb1fb3861689e4c5a6af5d5773a51068d9290 breaks the module for me.

Here are some different ways of importing submodules that might be helpful in your environment.
http://stackoverflow.com/questions/26849832/python-imports-relative-path 
http://stackoverflow.com/questions/5137082/django-python-modules-and-git-submodules

**Comment by mxpr** [comment]
I agree @dmueller39 - @yirenjun  thanks for spotting that bug will submit a separate fix for that shortly without the relative imports.

**Comment by mxpr** [comment]
#9 just merged to address the non Swift apps issue

**Comment by yirenjun** [comment]
@dmueller39 thanks

**Pull request closed without merging**
